### ISSUE TITLE
Adding Emoji Picker

### ISSUE THREAD

**Issue by Kopal777** [urstrulynishkarsh/ReactChat#11]
It can enhance user experience and make communication more fun and expressive. Please assign it to me.

**Comment by urstrulynishkarsh** [comment]
https://meet.google.com/cuz-ykih-muq
  Kindly join this meeting at 10pm today

**Comment by SumitKumar-17** [comment]
@Kopal777 I want to work on this issue. Can you assign this issue to me under GSSoc'24?
I can add it as I have added these feature in a personal project of mine.

**Comment by Jatingupta9120** [comment]
assign this issue to me

**Comment by abhiperfect** [comment]
Subject: Integration of Emoji Picker Feature

Hi @urstrulynishkarsh  ,

I hope you're doing well. I wanted to suggest an enhancement to our platform by integrating an emoji picker feature. This addition can enrich user interactions by allowing them to easily express themselves with emojis.

I'm eager to collaborate on this project and explore how we can seamlessly integrate an emoji picker into our platform's interface.

I am attaching a file related to it, i hope you want functionality like this.


Best regards,
Abhishek

![Screenshot 2024-05-03 210525](https://github.com/urstrulynishkarsh/ReactChat/assets/114478676/a2034e91-8152-4378-a9a3-bb1b14a55239)

**Comment by urstrulynishkarsh** [comment]
@Kopal777 tell me currently are your working or not on this task otherwise i will assign to other atleast you need to inform me

**Comment by SumitKumar-17** [comment]
@Kopal777  Can i start working on it . I had messaged you regarding it in this conversation.

**Comment by Kopal777** [comment]
I am working on it

**Comment by urstrulynishkarsh** [comment]
Ok, thanks for the update.

**Comment by abhiperfect** [comment]
> @Kopal777 tell me currently are your working or not on this task otherwise i will assign to other atleast you need to inform me

"Sir, if there's any chance to assign this task, I can fix this issue in a few hours."
