### ISSUE TITLE
Feat/Generate Random room id.

### ISSUE THREAD

**Issue by abhiperfect** [urstrulynishkarsh/ReactChat#116]
### Describe the feature

A button next to the "Room" label generates a random and unique Room ID for easy room creation and identification.

### It should be implemented because

It should be implemented because it simplifies the process of creating and identifying rooms, ensuring each room has a unique and easily generated ID.

### Would you like to work on this issue?

Yes

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by ParthNakum21** [comment]
Hello, I'm interested in contributing to the project by adding the functionality of generate unique room id. Could you please assign this task to me under GSSoC with appropriate level?
