### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [urstrulynishkarsh/ReactChat#14]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started

@urstrulynishkarsh  please assign this issue to me.

**Comment by urstrulynishkarsh** [comment]
How much time you will take

**Comment by jinx-vi-0** [comment]
@urstrulynishkarsh by tonight.

**Comment by urstrulynishkarsh** [comment]
Ok i am assigning

**Comment by urstrulynishkarsh** [comment]
@jinx-vi-0  current status???
