### ISSUE TITLE
Feat: Automate greeting using Github bot 🤖

### ISSUE THREAD

**Issue by shubhammjha22** [urstrulynishkarsh/ReactChat#153]
### Describe the feature

I would like to add a github bot , which would greet the user whenever there is a PR request or a issue raised
with something like

For PR
"Awesome work, @username! 🎉 Thank you for submitting pull request.
We truly appreciate your contribution and efforts to enhance our project.
Please ensure that you have followed the contributing guidelines for a smooth review process"

For Issue
"Hello @userName,
Thanks for creating this issue and contributing to Tourism!
@admin will review your issue soon and provide feedback. In the meantime, feel free to join the discord community. Please ensure that you have followed the contributing guidelines for a smooth review process"

### It should be implemented because

As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

### Additional context

![image](https://github.com/urstrulynishkarsh/ReactChat/assets/68507333/021bbffc-9ec0-4ea0-8395-f5f4a6c44656)

### Would you like to work on this issue?

Yes

**Comment by anshulsoni4** [comment]
@shubhammjha22 assigned you, good luck

**Comment by shubhammjha22** [comment]
@anshulsoni4 I have made the PR , kindly review it

**Comment by anshulsoni4** [comment]
> @anshulsoni4 I have made the PR , kindly review it

alright
