### ISSUE TITLE
[Feat]: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [urstrulynishkarsh/ReactChat#158]
### Describe the feature

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Additional context

![issue closed](https://github.com/urstrulynishkarsh/ReactChat/assets/115717746/04268bdf-4abd-43c0-8beb-c83a72bc3fbc)

### Would you like to work on this issue?

Yes

**Comment by anshulsoni4** [comment]
sure, go for it
