### ISSUE TITLE
Twitter Icon is not updated

### ISSUE THREAD

**Issue by Janani-m17** [urstrulynishkarsh/ReactChat#162]
### Describe your issue

The twitter is changed but it is not implemented in the website.
![image](https://github.com/urstrulynishkarsh/ReactChat/assets/124059957/7a90a36d-a0c6-44c9-86fa-c69b9fbb465c)

### Steps to reproduce

Click share option. 
It will display social media apps in that it is displaying old icon of twitter.

### What was the expected result?

The new icon should be updated for twitter.
![image](https://github.com/urstrulynishkarsh/ReactChat/assets/124059957/0413fdf3-f82c-4d8e-973a-5eeb20f9c956)

### Put here any screenshots or videos (optional)

![image](https://github.com/urstrulynishkarsh/ReactChat/assets/124059957/d87113c9-87f7-4d53-8533-91d882c57dd2)

### Would you like to work on this issue?

Yes

Please assign this issue to me sir.
@urstrulynishkarsh

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24

**Comment by amresh012** [comment]
Hey  Please assign me this issue
