### ISSUE TITLE
Make the website Mobile responsive

### ISSUE THREAD

**Issue by Yash-Ainapure** [urstrulynishkarsh/ReactChat#166]
### Describe the feature

The present website viewed in mobile looks like this:
![image](https://github.com/urstrulynishkarsh/ReactChat/assets/136250383/4d844fff-fdfd-4882-b008-c00c867ef5f3)

I will try the make the whole website mobile responsive as possible

### It should be implemented because

Improve User experience

### Would you like to work on this issue?

Yes

**Comment by Ankitmohanty2** [comment]
will u assign me this issue i will contribute to it

**Comment by Yash-Ainapure** [comment]
> will u assign me this issue i will contribute to it

Sir, I am only waiting for the owner to assign the issue to me

**Comment by anshulsoni4** [comment]
this issue is already in work by someone, try to add something more
