### ISSUE TITLE
user login and signup functionality and store user details

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [urstrulynishkarsh/ReactChat#168]
### Describe the feature

I suggest you to make a login and signup button and i can implement this with the help of firebase and mongodb both and also i suggest that try to store user in some cloud database so that for big user base your app work i can implement this issue

kindly assign me this issue under Gssoc'24

### Would you like to work on this issue?

None

**Comment by anshulsoni4** [comment]
i will ask from admin and let you know
