### ISSUE TITLE
I want to add a favicon for this chat app

### ISSUE THREAD

**Issue by AnitSarkar123** [urstrulynishkarsh/ReactChat#17]
Please assign me this under GSSoC'24  @urstrulynishkarsh

**Comment by urstrulynishkarsh** [comment]
Send me favicon icon

**Comment by AnitSarkar123** [comment]
@urstrulynishkarsh  what about this logo 
![chat-app logo](https://github.com/urstrulynishkarsh/ReactChat/assets/135215478/8b4b671e-ef32-4fe6-af8b-23202bd428c7)

**Comment by urstrulynishkarsh** [comment]
Yes, it works!
