### ISSUE TITLE
New User Chat History Access Button

### ISSUE THREAD

**Issue by rajat99-default** [urstrulynishkarsh/ReactChat#171]
### Describe the feature

The proposed feature is the addition of a button to the chat room interface that allows new users to access the previous chat history. This button will be prominently displayed on the screen when a new user joins the chat room.

### It should be implemented because

Currently, when a new user joins the chat room, they are unable to view the previous messages that were sent before they joined

### Would you like to work on this issue?

Yes

**Comment by anshulsoni4** [comment]
okay assigning you this, by the time let me know how will you achieve this

**Comment by rajat99-default** [comment]
> okay assigning you this, by the time let me know how will you achieve this

Bro 
Do you know coding?

**Comment by rajat99-default** [comment]
> okay assigning you this, by the time let me know how will you achieve this

Bhai ye level 3 ki problem hai

**Comment by anshulsoni4** [comment]
> > okay assigning you this, by the time let me know how will you achieve this
> 
> Bro Do you know coding?

do you want to work in this??
or i will remove you 

but this kind of language is not tolerated

**Comment by anshulsoni4** [comment]
@rajat99-default I am talking to the Org members now, they will get you removed from the program 
because this is not under our guidelines

**Comment by urstrulynishkarsh** [comment]
@anshulsoni4  you can close this req and if you found anything wrong just close it
