### ISSUE TITLE
Twitter icon should be replaced with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [urstrulynishkarsh/ReactChat#173]
### Describe your issue

![image](https://github.com/urstrulynishkarsh/ReactChat/assets/140897461/336f218b-1122-466d-b256-a7c6b1def823)
### Steps to reproduce

replace twitter icon with x icon

### What was the expected result?

More professional outlook

### Would you like to work on this issue?

Yes

**Comment by anshulsoni4** [comment]
assigning you this issue @AkhilaSunesh
