### ISSUE TITLE
fix for MOBILE screen to improve messaging

### ISSUE THREAD

**Issue by Utsavladia** [urstrulynishkarsh/ReactChat#175]
### Describe the feature

the messaging feature is not well organised for the mobile screeen 
It should be fixed to use it on all devices properly.

![image](https://github.com/urstrulynishkarsh/ReactChat/assets/124615886/0e733cc7-072b-477a-bc5a-25cb626e1336)

### Would you like to work on this issue?

Yes

**Comment by anshulsoni4** [comment]
this issue is already been assigned, if it does not get completed i will assign you this
