### ISSUE TITLE
While entering room number only number should allow 

### ISSUE THREAD

**Issue by kapilG0** [urstrulynishkarsh/ReactChat#177]
### Describe your issue

![Screenshot_20240604_170155](https://github.com/urstrulynishkarsh/ReactChat/assets/59639410/d771bb9e-507a-4507-83e7-9ecd5a13d3b0)

### Steps to reproduce

Go to home page 

### Would you like to work on this issue?

Yes

**Comment by kapilG0** [comment]
Hello @urstrulynishkarsh please assign this issue to me under gssoc 24

**Comment by anshulsoni4** [comment]
hey @kapilG0 can you brief me about this and i'll assign you

**Comment by kapilG0** [comment]
> hey @kapilG0 can you brief me about this and i'll assign you

As you can see in above image I am passing fh in room number which should not allowed I mean only number should allow @anshulsoni4
