### ISSUE TITLE
Send messages on right and receive on left side🌟

### ISSUE THREAD

**Issue by anurag-adk** [urstrulynishkarsh/ReactChat#178]
### Describe the feature

The feature will change the alignment of chat messages in the application so that the user's sent messages appear on the right side of the chat window, while messages received from others appear on the left side. This aligns with common messaging app layouts, making the interface more intuitive and user-friendly.

Currently, It looks like this:
![image](https://github.com/urstrulynishkarsh/ReactChat/assets/89135704/8d2f6c36-d245-4b84-ae17-ce084af4494a)

I think this can be improved

### It should be implemented because

Changing the alignment of messages will enhance the usability and visual appeal of the chat application. Users are generally accustomed to this layout from other popular messaging platforms, which will undoubtly improve the user experience.

### Additional context

This change can be accompanied by minor UI tweaks like speech bubble styles for sent and received messages to further distinguish between them.

### Would you like to work on this issue?

Yes

**Comment by anurag-adk** [comment]
@urstrulynishkarsh I would love to work on this issue under gssoc label

**Comment by anshulsoni4** [comment]
> @urstrulynishkarsh I would love to work on this issue under gssoc label

all the best @anurag-adk will be watching your PR now

**Comment by anurag-adk** [comment]
Thanks, @anshulsoni4 Can you also add a level label to it?

**Comment by anshulsoni4** [comment]
> Thanks, @anshulsoni4 Can you also add a level label to it?

done, good luck!
