### ISSUE TITLE
Enable Emoji Sending Capability in Chat Room

### ISSUE THREAD

**Issue by Prateek579** [urstrulynishkarsh/ReactChat#181]
### Describe the feature

We've noticed that users are currently unable to send emojis within our chat room feature. To enhance user experience and foster better communication, we're planning to introduce an emoji sending feature.

### It should be implemented because

This will allow users to express themselves more creatively and effectively during conversations. Let's discuss the implementation details and timeline for integrating this feature seamlessly into our platform.

### Would you like to work on this issue?

None

**Comment by anshulsoni4** [comment]
Please check this issue has been already created
