### ISSUE TITLE
[Feat]: Enhancing the UI of elements in the chat interface

### ISSUE THREAD

**Issue by Asymtode712** [urstrulynishkarsh/ReactChat#182]
### Describe the feature

The feature involves enhancing the User Interface (UI) of elements in the chat interface. This would include improving the visual design and making the chat elements more intuitive and user-friendly. Enhancements would cover aspects such as message bubbles, input fields, buttons,  and overall layout adjustments to improve the aesthetic appeal and functionality.

### It should be implemented because

Improved UI enhances the overall user experience, making the chat interface more enjoyable and easier to use. Improved UI can streamline interactions, making it quicker for users to send and receive messages, thus increasing productivity. A visually appealing and intuitive interface can increase user engagement and satisfaction.

### Additional context

![Annotation 2024-06-08 111720](https://github.com/urstrulynishkarsh/ReactChat/assets/115717746/2604170b-27bf-4aec-b336-e52277370842)

### Would you like to work on this issue?

Yes

**Comment by Asymtode712** [comment]
@anshulsoni4 Please assign me this issue

**Comment by anshulsoni4** [comment]
alright

**Comment by Asymtode712** [comment]
@anshulsoni4 Why is this issue closed??
