### ISSUE TITLE
Implement Auto-Comment Feature for PRs

### ISSUE THREAD

**Issue by thevijayshankersharma** [urstrulynishkarsh/ReactChat#194]
### Describe the feature

Develop a feature to automatically generate comments for pull requests (PRs) raised 

### It should be implemented because

The aim is to streamline the PR review process by providing a standardized comment format, enhancing clarity and efficiency in communication between contributors and reviewers.

### Would you like to work on this issue?

Yes

**Comment by anshulsoni4** [comment]
already done, thanks

**Comment by thevijayshankersharma** [comment]
> already done, thanks

![image](https://github.com/urstrulynishkarsh/ReactChat/assets/109781385/e821797d-71c0-4fc2-af94-79a9f2d95226)

as you can see there is not. Or else you can check the PRs there is no greeting or any other auto comment
