### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by Princegupta101** [urstrulynishkarsh/ReactChat#4]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by asr2003** [comment]
@IP80808080 If you can also submit videos it could be great in Learning.md. Please follow the issue description and adding level 2 for now. If you submit videos too we are ready to assign a Level 3

**Comment by IP80808080** [comment]
Hello Sir,

I have submitted a pull request for issue https://github.com/urstrulynishkarsh/ReactChat/issues/4, which includes a video explanation for better understanding. I kindly request you to review the pull request and consider it for leveling up to level 3. 🌟
