### ISSUE TITLE
Typing.. indicator is not showing 

### ISSUE THREAD

**Issue by sahib139** [urstrulynishkarsh/ReactChat#42]
### Describe the feature

When the user starts typing the message in a room, then no typing indicator is shown to other users in the same room. I want to implement this feature.

### It should be implemented because

This feature will increase user activity and it's a good idea to include typing indicators in your chat app to improve the chat experience.

### Would you like to work on this issue?

Yes

**Comment by urstrulynishkarsh** [comment]
@sahib139  i think its  working properly you can check it from two windows

**Comment by urstrulynishkarsh** [comment]
come on room no 1
