### ISSUE TITLE
 Enhancing Centered Join Card Form Design

### ISSUE THREAD

**Issue by dhruv389** [urstrulynishkarsh/ReactChat#54]
### Describe the feature

The feature involves enhancing the design of a centered join card form. Currently, the form appears simplistic with basic input tags, lacking visual appeal and engagement. The goal is to transform this form into a stylish and visually captivating component that effectively captures users' attention and encourages interaction.

![image](https://github.com/urstrulynishkarsh/ReactChat/assets/117587892/ed19e352-287f-4824-a8c0-f1c6504335d5)

### It should be implemented because

Enhancing the design of the join card form is crucial for improving user experience and increasing user engagement. A visually appealing and stylish form not only attracts users but also instills confidence and trust in the brand. By implementing this feature, we can create a more immersive and delightful user experience, ultimately leading to higher conversion rates and user satisfaction.

### Additional context

Hello @urstrulynishkarsh ,
Please assign me this issue  , i want to work on it.

### Would you like to work on this issue?

Yes

**Comment by urstrulynishkarsh** [comment]
some one also work on it
