### ISSUE TITLE
UI Enhancement, File Management Improvement, and State Management Fix

### ISSUE THREAD

**Issue by BhattAnsh** [urstrulynishkarsh/ReactChat#9]
**Pull Request Description**
This pull request aims to enhance the user interface (UI), improve file management, and address state management issues in the chat application. The current UI lacks visual appeal and interactivity compared to other applications, leading to a subpar user experience. Additionally, the file management structure can be optimized for better organization and ease of maintenance. Furthermore, certain components are not functioning correctly due to state management issues, which need to be resolved for the application to work seamlessly.

### **Changes Proposed**
**UI Enhancement:**
Update the color combination and styling to create a more soothing and visually appealing interface for the chat application, aligning it with industry standards and user expectations.

Introduce interactive elements to enhance user engagement and make the chat experience more dynamic and enjoyable.

**File Management Improvement:**
Restructure the file organization by moving CSS files to a separate folder, improving the project's organization and making it easier to locate and manage styling resources.

**State Management Fix:**
Identify and resolve issues with state management that are causing components to malfunction or behave unpredictably.

Ensure proper implementation of state management techniques such as Redux or Context API to maintain consistent application state and facilitate efficient data flow.

### **Expected Outcome**
A visually enhanced chat application with improved color combination, interactive elements, and overall UI aesthetics, resulting in a more engaging and enjoyable user experience.

Enhanced file management structure with CSS files stored in a separate folder, improving project organization and developer productivity.

Improved state management implementation, ensuring smooth functionality and reliable performance of chat components.

**Comment by BhattAnsh** [comment]
Assign me this issue for GSSOC'24 i've worked on the react app projects you can see my github repos.

**Comment by urstrulynishkarsh** [comment]
Sure i will connect at 10 pm

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by asr2003** [comment]
@BhattAnsh Given Level 3 to Fix State Management

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. I have just finished one Issue, Could you please assign it to me? Thank you! 🚀

**Comment by urstrulynishkarsh** [comment]
@IP80808080  wait @BhattAnsh  is working right now

**Comment by urstrulynishkarsh** [comment]
@BhattAnsh current status

**Comment by BhattAnsh** [comment]
@urstrulynishkarsh ui is ready and  made changes in the folders to structure them but for my exams are going on so I can't fully work on it right now after this upcoming Sunday I will give my all time to it.

**Comment by urstrulynishkarsh** [comment]
No problem, take your time. Send me figma design if you have it

**Comment by BhattAnsh** [comment]
@urstrulynishkarsh I will share it with you don't worry about work I will do it once I start working on the coding part and about figma I have to make a separate file for that I will share it with u soon

**Comment by urstrulynishkarsh** [comment]
@Venkatknight2295

**Comment by Venkatknight2295** [comment]
@BhattAnsh let me do this work or let’s collaborate and complete this work if you agree

**Comment by BhattAnsh** [comment]
@Venkatknight2295 You can collaborate with me for this work drop me your discord Id I will tell you what to do and raise a issue and @urstrulynishkarsh will assign you the issue and you can start working on it.

**Comment by urstrulynishkarsh** [comment]
@BhattAnsh  update status

**Comment by BhattAnsh** [comment]
> @BhattAnsh  update status

I've started working on chat's ui and it is working but there is an issue in fetching messages since I am making to different message container like one which user sent and one is for me I've sent the code to one of my friend who is debugging it will update u shortly more about it. Okay.? And I've created proper hierarchy system in folders I will make commit when the work is completed

**Comment by urstrulynishkarsh** [comment]
Ok, thanks for the update.
